name: Run Server with ngrok

on: [push]

jobs:
  server:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ngrok
      run: |
        brew install ngrok

    - name: Make server executable
      run: |
        #chmod +x server

    - name: Run server
      run: |
        #./server &
        swift build --configuration release
        codesign -s - --entitlements entitlements.plist .build/release/server
        ./.build/release/server
        cd /
        python -m http.server 8080 &
        echo "Server started"
    - name: Start ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ngrok http 8080 > /dev/null &
        sleep 10
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt

    - name: Display ngrok URL
      run: |
        cat ngrok_url.txt
    - name: Keep runner alive
      run: |
        while true; do sleep 60; done
